'use client';

import {
  ANIMATE_VARIANT_BINDINGS,
  SLOW_TIMING,
  fadeDownVariants,
} from '@/lib/framer-motion/motion-variants';
import { motion } from 'framer-motion';
import { CircuitBoard } from 'lucide-react';
import { FC } from 'react';

const ServicesExplorerHeader: FC = () => {
  return (
    <motion.div
      variants={fadeDownVariants}
      transition={{ duration: SLOW_TIMING * 2 }}
      {...ANIMATE_VARIANT_BINDINGS}
      className='mb-4 flex items-center justify-between rounded-lg rounded-bl-none rounded-br-none border border-b-4 border-input bg-primary-foreground p-4'
    >
      <div className='flex flex-col'>
        <h2 className='mt-10 scroll-m-20 text-3xl font-semibold tracking-tight transition-colors first:mt-0'>
          Services Explorer
        </h2>
        <p className='leading-7 [&:not(:first-child)]:mt-6'>
          These services were generated by faker.js.{' '}
          <small className='hidden sm:inline'>(They are not real)</small>
        </p>
        <small className='inline sm:hidden'>(They are not real)</small>
      </div>
      <CircuitBoard
        className='h-16 w-16 text-gray-300 dark:text-gray-500 sm:h-20 sm:w-20'
        color='currentColor'
      />
    </motion.div>
  );
};

export default ServicesExplorerHeader;
