import AppThemeProvider from "@/contexts/AppThemeContext";
import "./global.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <AppThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </AppThemeProvider>
      </body>
    </html>
  );
}
