import { promises as fs } from 'fs';
import path from 'path';
import { Metadata } from 'next';
import { z } from 'zod';

import { ServicesDataTable } from '@/components/services/ServicesDataTable';
import PageWrapper from '@/components/app/PageWrapper';
import { serviceSchema } from '@/features/services/data/schema';
import { servicesDataTableColumns } from '@/components/services/ServicesDataTableColumns';
import { CircuitBoard } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Services Playground',
  description: 'A services tracker built using Tanstack Table.',
};

// Simulate a database read for services.
async function getServices() {
  const data = await fs.readFile(
    path.join(process.cwd(), 'src/features/services/data/services.json')
  );

  const services = JSON.parse(data.toString());

  return z.array(serviceSchema).parse(services);
}

export default async function ServicesPlaygroundPage() {
  const services = await getServices();

  return (
    <PageWrapper titleText='Service Playground'>
      <section
        data-purpose-id='services-content'
        className='flex w-full grow flex-col px-4 py-4 md:container'
      >
        <div className='mb-4 flex items-center justify-between rounded-lg rounded-bl-none rounded-br-none border border-b-4 border-input bg-primary-foreground p-4'>
          <div className='flex flex-col'>
            <h2 className='mt-10 scroll-m-20 text-3xl font-semibold tracking-tight transition-colors first:mt-0'>
              Services Explorer
            </h2>
            <p className='leading-7 [&:not(:first-child)]:mt-6'>
              These services were generated by faker.js.{' '}
              <small className='hidden sm:inline'>(They are not real)</small>
            </p>
            <small className='inline sm:hidden'>(They are not real)</small>
          </div>
          <CircuitBoard
            className='h-16 w-16 text-gray-300 sm:h-20 sm:w-20'
            color='currentColor'
          />
        </div>
        <ServicesDataTable data={services} columns={servicesDataTableColumns} />
      </section>
    </PageWrapper>
  );
}
